import { useEffect, useState } from "react";
import { BrainCircuit, FileText, LoaderCircle, Sparkles } from "lucide-react";
import Navbar from "../../components/layout/Navbar";
import api from "../../api/axios";

const fields = [["Research problem", "researchProblem"], ["Methodology", "methodology"], ["Key findings", "keyFindings"], ["Limitations", "limitations"], ["Conclusion", "conclusion"]];

export default function ResearchAssistant() {
  const [papers, setPapers] = useState([]); const [paperId, setPaperId] = useState(""); const [summary, setSummary] = useState(null); const [loading, setLoading] = useState(true); const [generating, setGenerating] = useState(false); const [error, setError] = useState("");
  useEffect(() => { api.get("/api/papers").then(({ data }) => { const list = data.papers || []; setPapers(list); if (list[0]) setPaperId(list[0]._id); }).catch((err) => setError(err.response?.data?.message || "Unable to load papers.")).finally(() => setLoading(false)); }, []);
  const generate = async () => { if (!paperId) return; setGenerating(true); setError(""); setSummary(null); try { const { data } = await api.post(`/api/ai/summarize/${paperId}`); setSummary(data.summary); } catch (err) { setError(err.response?.data?.message || "Unable to generate a summary."); } finally { setGenerating(false); } };
  return <div className="min-h-screen bg-[#FAF7FF]"><Navbar /><main className="mx-auto max-w-5xl px-6 py-10"><section className="rounded-[2rem] border border-violet-100 bg-white p-8 shadow-sm"><div className="flex items-start gap-4"><div className="rounded-2xl bg-violet-100 p-3 text-violet-700"><BrainCircuit /></div><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-violet-600">AI research assistant</p><h1 className="mt-2 text-3xl font-bold text-slate-900">Understand a paper faster</h1><p className="mt-3 max-w-2xl text-slate-600">Generate a structured, academic summary from the text extracted from one of your PDFs.</p></div></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="paper">Choose a paper</label><select id="paper" value={paperId} onChange={(event) => setPaperId(event.target.value)} disabled={loading || generating} className="min-w-0 flex-1 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-slate-800 outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-100"><option value="">Select a paper</option>{papers.map((paper) => <option key={paper._id} value={paper._id}>{paper.title || paper.filename}</option>)}</select><button onClick={generate} disabled={!paperId || generating} className="inline-flex items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-violet-600 to-fuchsia-500 px-5 py-3 font-semibold text-white shadow-md transition hover:shadow-lg disabled:cursor-not-allowed disabled:opacity-50">{generating ? <LoaderCircle size={18} className="animate-spin" /> : <Sparkles size={18} />}{generating ? "Analyzing…" : "Generate summary"}</button></div>{loading ? <div className="mt-6 flex justify-center text-violet-600"><LoaderCircle className="animate-spin" /></div> : !papers.length && !error ? <p className="mt-6 rounded-2xl bg-violet-50 p-4 text-sm text-violet-800">Upload a PDF first to use the assistant.</p> : null}{error ? <p className="mt-6 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{error}</p> : null}</section>{summary ? <section className="mt-8 rounded-3xl border border-violet-100 bg-white p-8 shadow-sm"><div className="flex items-center gap-3"><FileText className="text-violet-600" /><div><p className="text-sm font-medium text-violet-600">Generated summary</p><h2 className="text-2xl font-bold text-slate-900">{summary.title || "Paper analysis"}</h2></div></div>{summary.overview ? <p className="mt-6 leading-7 text-slate-700">{summary.overview}</p> : null}<div className="mt-8 grid gap-4 md:grid-cols-2">{fields.map(([label, key]) => summary[key] ? <article key={key} className="rounded-2xl bg-slate-50 p-5"><h3 className="font-bold text-slate-800">{label}</h3><p className="mt-2 whitespace-pre-line text-sm leading-6 text-slate-600">{Array.isArray(summary[key]) ? summary[key].join("\n• ") : summary[key]}</p></article> : null)}</div></section> : null}</main></div>;
}
