import { useEffect, useState } from "react";
import { FolderKanban, LoaderCircle, FileText, ArrowRight } from "lucide-react";
import Navbar from "../../components/layout/Navbar";
import api from "../../api/axios";

export default function Projects() {
  const [workspaces, setWorkspaces] = useState([]);
  const [selected, setSelected] = useState(null);
  const [papers, setPapers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState("");

  useEffect(() => { api.get("/api/workspaces").then(({ data }) => setWorkspaces(data.workspaces || [])).catch((err) => setMessage(err.response?.data?.message || "Unable to load projects.")).finally(() => setLoading(false)); }, []);
  const openWorkspace = async (workspace) => { setSelected(workspace); setPapers([]); setMessage(""); try { const { data } = await api.get(`/api/workspaces/${workspace._id}/papers`); setPapers(data.papers || []); } catch (err) { setMessage(err.response?.data?.message || "Unable to load this project."); } };

  return <div className="min-h-screen bg-[#FAF7FF]"><Navbar /><main className="mx-auto max-w-7xl px-6 py-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-violet-600">Collections</p><h1 className="mt-2 text-4xl font-bold text-slate-900">Research projects</h1><p className="mt-3 text-slate-600">Papers are grouped automatically by their detected topic.</p></div></div>{loading ? <div className="flex justify-center py-20 text-violet-600"><LoaderCircle className="animate-spin" /></div> : message && !selected ? <p className="mt-8 rounded-2xl bg-rose-50 p-4 text-rose-700">{message}</p> : workspaces.length ? <div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{workspaces.map((workspace) => <button type="button" key={workspace._id} onClick={() => openWorkspace(workspace)} className="group rounded-3xl border border-violet-100 bg-white p-6 text-left shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><FolderKanban className="text-violet-600" /><h2 className="mt-5 text-xl font-bold text-slate-900">{workspace.name}</h2><p className="mt-2 min-h-12 text-sm leading-6 text-slate-500">{workspace.description || "Research collection"}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-semibold text-violet-600">View papers <ArrowRight size={16} className="transition group-hover:translate-x-1" /></span></button>)}</div> : <div className="mt-8 rounded-3xl border border-dashed border-violet-200 bg-white p-12 text-center"><FolderKanban className="mx-auto text-violet-400" size={34} /><h2 className="mt-4 text-xl font-bold">No projects yet</h2><p className="mt-2 text-slate-500">Upload a PDF and ResearchNest will create a topic collection for it.</p></div>}{selected && <section className="mt-10 rounded-3xl border border-violet-100 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-medium text-violet-600">Project papers</p><h2 className="mt-1 text-2xl font-bold">{selected.name}</h2></div><button onClick={() => setSelected(null)} className="text-sm font-semibold text-slate-500 hover:text-slate-900">Close</button></div>{message ? <p className="mt-5 text-sm text-rose-600">{message}</p> : papers.length ? <div className="mt-5 grid gap-3">{papers.map((paper) => <div key={paper._id} className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><FileText className="text-violet-600" size={19} /><div className="min-w-0"><p className="truncate font-semibold text-slate-800">{paper.title || paper.filename}</p><p className="truncate text-sm text-slate-500">{paper.authors?.join(", ") || "Unknown authors"}</p></div></div>)}</div> : <p className="mt-5 text-sm text-slate-500">No papers in this project.</p>}</section>}</main></div>;
}
